### ISSUE TITLE
fix for ubuntu dialog version

### ISSUE THREAD

**Issue by CoreSec-xyz** [elbosso/expect-dialog-ca#30]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=915949

**Comment by elbosso** [comment]
scheint so, dass das nur die Dateiauswahl betrifft. Das lässt sich mittels `tput` aus `ncurses-bin` lösen - damit kann man herausfinden, wieviele Zeilen und Spalten das Terminal hat und dann explizit eine Größe vorgeben...
https://stackoverflow.com/questions/263890/how-do-i-find-the-width-height-of-a-terminal-window
muss aber noch getestet werden...
